<a href="https://colab.research.google.com/github/Fastina-Angel/Datascience-programs/blob/main/DS_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)

total=np.sum(marks)
print(total)

avg=np.average(marks)
print(avg)

max=np.max(marks)
print(max)
min=np.min(marks)
print(min)

#find the students who scored above 75
above75=marks[marks>75]
print(above75)

#marks less than or = to 50
below50=marks[marks<=50]
print(below50)

#sorted array
sorted=np.sort(marks)
print(sorted)

[78 92 65 88 45 90 72 55]
585
73.125
92
45
[78 92 88 90]
[45]
[45 55 65 72 78 88 90 92]


In [ ]:
# array containing range of values from 1 to 20
array1=np.arange(1,21)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
array2=np.ones(4)
array3=np.zeros(5)

print(array2)
print(array3)

[1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [ ]:
array4=np.random.randint(1,100,10)
print(array4)
print(array4.shape)

[74 44 72 14 65 71 80 19  6  5]
(10,)


In [ ]:
temp=np.array([32,35,40,28,42,33])

mean=np.average(temp)
print(mean)

max=np.max(temp)
min=np.min(temp)
print(max,min)

replce=temp[temp>=38]=38
print(temp)

temp2=temp.reshape(2,3)
print(temp2)

print(temp2[0]) #first row
print(temp2[0,1])
print(temp2[:,1]) #second column

35.0
42 28
[32 35 38 28 38 33]
[[32 35 38]
 [28 38 33]]
[32 35 38]
35
[35 38]


In [ ]:
arr=np.array([10,20,30,40,50,60,70,80])

print(arr[0::7]) #first element& last element
print(arr[2:7])  #elements from inx 2 to 6

print(arr[0:7:2])

[10 80]
[30 40 50 60 70]
[10 30 50 70]


In [ ]:
arr1=np.array([10,21,36,40,59,60,73,80])
print(arr1)

print(np.where(arr1%2==0))  #index of even no. (using where, for index)
print(arr1[arr1%2==0])  #even numbers (without where, for elements)

print(np.where(arr1%2!=0)) #index of odd no.  ,,
print(arr1[arr1%2!=0]) #odd numbers

[10 21 36 40 59 60 73 80]
(array([0, 2, 3, 5, 7]),)
[10 36 40 60 80]
(array([1, 4, 6]),)
[21 59 73]
